# Generated by Django 4.0.5 on 2022-06-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('1', 'ADMINISTRADOR'), ('2', 'ECONOMISTA'), ('3', 'OTRO'), ('0', 'CONTADOR')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
