# Generated by Django 4.0.5 on 2022-07-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_habilidades_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidades',
            field=models.ManyToManyField(to='persona.habilidades'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('2', 'ECONOMISTA'), ('0', 'CONTADOR'), ('3', 'OTRO'), ('1', 'ADMINISTRADOR')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
