# Generated by Django 4.0.5 on 2022-07-05 18:10

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_empleado_habilidades_alter_empleado_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='hoja_vida',
            field=ckeditor.fields.RichTextField(default='texto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('2', 'ECONOMISTA'), ('3', 'OTRO'), ('1', 'ADMINISTRADOR'), ('0', 'CONTADOR')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
