# Generated by Django 4.0.6 on 2022-07-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0006_alter_empleado_options_empleado_full_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='hoja_vida',
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('1', 'ADMINISTRADOR'), ('3', 'OTRO'), ('2', 'ECONOMISTA'), ('0', 'CONTADOR')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
