# Generated by Django 4.0.6 on 2022-07-13 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_remove_empleado_hoja_vida_alter_empleado_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombres Completos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('0', 'CONTADOR'), ('1', 'ADMINISTRADOR'), ('3', 'OTRO'), ('2', 'ECONOMISTA')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
