# Generated by Django 4.0.6 on 2022-07-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_alter_empleado_full_name_alter_empleado_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('1', 'ADMINISTRADOR'), ('3', 'OTRO'), ('0', 'CONTADOR'), ('2', 'ECONOMISTA')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
