# Generated by Django 4.0.6 on 2022-08-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0009_alter_empleado_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='job',
            field=models.CharField(choices=[('2', 'ECONOMISTA'), ('1', 'ADMINISTRADOR'), ('3', 'OTRO'), ('0', 'CONTADOR')], max_length=50, verbose_name='Trabajo'),
        ),
    ]
